# Generated by Django 4.2.28 on 2026-06-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0030_alter_map_map_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="map_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zone_humide", "Zone humide"),
                    ("zone_inondable", "Zone inondable"),
                    ("species", "Espèces protégées"),
                    ("haies", "Haies"),
                    ("terres_emergees", "Délimitation terres + France"),
                    ("zonage", "Identifiant zonage"),
                    ("zone_sensible_ep", "Zone sensible EP"),
                    ("zv_nitrates", "Zone vulnérable nitrates"),
                    ("zone_action_renforcee", "Zone action renforcée nitrates"),
                    ("rpg_parcelle", "Parcelle RPG"),
                ],
                max_length=50,
                verbose_name="Map type",
            ),
        ),
    ]
