# Generated by Django 4.2.30 on 2026-09-24 07:36
#
# REVERT_AT_MERGE_TIME_FOR_UPSTREAM_ENVERGO
#
# Versioning des couches SIG nitrates : plusieurs millesimes d'une meme
# couche coexistent, un seul est actif. Le backfill etiquette les couches
# deja en base avec leur millesime reel, pour qu'on sache d'ou on part.

from django.db import migrations, models

# Millesime des couches deja en base au moment de l'introduction du
# versioning. Cle = Map.name, valeur = version.
MILLESIMES_INITIAUX = {
    "ZV nitrates — national": "2021",
    "zar_par7_grand_est": "2024",
}


def backfill_versions(apps, schema_editor):
    """Etiquette les couches existantes. Tout reste actif : la migration
    ne change aucun comportement, elle nomme juste l'existant."""
    Map = apps.get_model("geodata", "Map")
    for name, version in MILLESIMES_INITIAUX.items():
        Map.objects.filter(name=name, version="").update(version=version)


def unbackfill_versions(apps, schema_editor):
    Map = apps.get_model("geodata", "Map")
    for name, version in MILLESIMES_INITIAUX.items():
        Map.objects.filter(name=name, version=version).update(version="")


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0031_alter_map_map_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Un seul millésime actif par (name, map_type). Les requêtes métier ne voient que les couches actives.",
                verbose_name="Millésime actif ?",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="Ex. « 2026 ». Vide = couche historique non versionnée.",
                max_length=32,
                verbose_name="Millésime de la couche",
            ),
        ),
        migrations.AddIndex(
            model_name="map",
            index=models.Index(
                fields=["map_type", "is_active"], name="geodata_map_map_typ_f03f82_idx"
            ),
        ),
        migrations.RunPython(backfill_versions, unbackfill_versions),
    ]
