# Generated by Django 4.2.28 on 2026-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RpgCulture",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("libelle", models.CharField(max_length=255)),
                ("code_groupe", models.CharField(blank=True, max_length=10)),
                ("libelle_groupe", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Code culture RPG",
                "verbose_name_plural": "Codes culture RPG",
                "ordering": ["code"],
            },
        ),
    ]
