# Generated by Django 4.2.28 on 2026-04-29 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nitrates", "0002_setup_moulinette_pattern"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("active", "Actif"),
                            ("archive", "Archive"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("contenu", models.JSONField()),
                ("contenu_yaml_brut", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="nitrates.decisiontree",
                    ),
                ),
            ],
            options={
                "ordering": ["-activated_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="nitrates_de_status_0f452d_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="decisiontree",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("status",),
                name="nitrates_decisiontree_unique_active",
            ),
        ),
    ]
