# Generated by Django 4.2.28 on 2026-04-30 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nitrates", "0005_decisiontree_lock"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionTreeRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("edit", "Édition"),
                            ("add", "Ajout"),
                            ("delete", "Suppression"),
                            ("rename", "Renommage"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_path", models.CharField(blank=True, max_length=500)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("previous_contenu", models.JSONField()),
                ("previous_yaml_brut", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="nitrates.decisiontree",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tree", "-created_at"],
                        name="nitrates_de_tree_id_eb9d75_idx",
                    )
                ],
            },
        ),
    ]
