# Generated by Django 4.2.28 on 2026-05-08 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import envergo.nitrates.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nitrates", "0006_decisiontreerevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decisiontreerevision",
            name="action",
            field=models.CharField(
                choices=[
                    ("edit", "Édition"),
                    ("add", "Ajout"),
                    ("delete", "Suppression"),
                    ("rename", "Renommage"),
                    ("restore", "Restauration"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="BrancheValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chemin_yaml",
                    models.CharField(
                        help_text="Path d'ids YAML depuis la racine vers la feuille",
                        max_length=1000,
                        unique=True,
                    ),
                ),
                ("regle_id", models.CharField(blank=True, max_length=200)),
                (
                    "branche_label",
                    models.CharField(
                        help_text="Chemin metier lisible (ex: 'sous_culture=colza / type_fertilisant=type_III')",
                        max_length=500,
                    ),
                ),
                (
                    "yaml_snapshot",
                    models.TextField(
                        blank=True,
                        help_text="Extrait YAML de la regle au moment du seed (round-trip)",
                    ),
                ),
                (
                    "branche_miro",
                    models.CharField(
                        blank=True,
                        help_text="Slug branche cote Miro (colza, luzerne, ...)",
                        max_length=200,
                    ),
                ),
                ("type_fertilisant_miro", models.CharField(blank=True, max_length=50)),
                ("condition_miro", models.CharField(blank=True, max_length=200)),
                ("zonage_miro", models.CharField(blank=True, max_length=200)),
                (
                    "resultat_miro",
                    models.CharField(
                        blank=True,
                        help_text="Texte resultat attendu cote Miro (ex 'Interdit du 15/12 au 15/01')",
                        max_length=500,
                    ),
                ),
                ("code_pc_miro", models.CharField(blank=True, max_length=20)),
                (
                    "screenshot_miro",
                    models.ImageField(
                        blank=True,
                        help_text="PNG Miro auto-attache depuis snapshot_miro/.../<branche>.png",
                        null=True,
                        upload_to=envergo.nitrates.models._branche_screenshot_path,
                    ),
                ),
                (
                    "screenshot_yaml_viewer",
                    models.ImageField(
                        blank=True,
                        help_text="Capture admin YAML viewer scrolle sur la feuille",
                        null=True,
                        upload_to=envergo.nitrates.models._branche_screenshot_path,
                    ),
                ),
                (
                    "screenshot_yaml_form",
                    models.ImageField(
                        blank=True,
                        help_text="Capture du form d'edition du noeud (cas tricky)",
                        null=True,
                        upload_to=envergo.nitrates.models._branche_screenshot_path,
                    ),
                ),
                (
                    "url_simulateur",
                    models.CharField(
                        blank=True,
                        help_text="URL relative du simulateur pre-rempli pour cette feuille",
                        max_length=2000,
                    ),
                ),
                (
                    "screenshot_playwright",
                    models.ImageField(
                        blank=True,
                        help_text="Capture du resultat simulateur (devops manuel)",
                        null=True,
                        upload_to=envergo.nitrates.models._branche_screenshot_path,
                    ),
                ),
                ("playwright_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_valide", "Non validé"),
                            ("valide", "Validé"),
                            ("a_corriger", "À corriger"),
                        ],
                        default="non_valide",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("valide_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branches_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation de branche",
                "verbose_name_plural": "Validations de branches",
                "ordering": ["chemin_yaml"],
            },
        ),
    ]
