# Generated by Django 4.2.28 on 2026-05-08 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import envergo.nitrates.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nitrates", "0006_decisiontreerevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decisiontreerevision",
            name="action",
            field=models.CharField(
                choices=[
                    ("edit", "Édition"),
                    ("add", "Ajout"),
                    ("delete", "Suppression"),
                    ("rename", "Renommage"),
                    ("restore", "Restauration"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="BrancheValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regle_id", models.CharField(max_length=200, unique=True)),
                (
                    "branche_label",
                    models.CharField(
                        help_text="Chemin metier lisible (ex: 'culture_principale > colza > type_III > note_5')",
                        max_length=500,
                    ),
                ),
                (
                    "yaml_snapshot",
                    models.TextField(
                        blank=True,
                        help_text="Extrait YAML de la regle au moment du seed (round-trip)",
                    ),
                ),
                (
                    "url_simulateur",
                    models.CharField(
                        blank=True,
                        help_text="URL relative du simulateur pre-rempli pour cette feuille",
                        max_length=2000,
                    ),
                ),
                (
                    "screenshot_miro",
                    models.ImageField(
                        blank=True,
                        help_text="Capture du Miro juriste pour cette branche (uploade par Max)",
                        null=True,
                        upload_to=envergo.nitrates.models._branche_screenshot_path,
                    ),
                ),
                (
                    "screenshot_playwright",
                    models.ImageField(
                        blank=True,
                        help_text="Capture auto Playwright du resultat simulateur",
                        null=True,
                        upload_to=envergo.nitrates.models._branche_screenshot_path,
                    ),
                ),
                ("playwright_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_valide", "Non validé"),
                            ("valide", "Validé"),
                            ("a_corriger", "À corriger"),
                        ],
                        default="non_valide",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("valide_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branches_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation de branche",
                "verbose_name_plural": "Validations de branches",
                "ordering": ["branche_label"],
            },
        ),
    ]
