# Generated by Django 4.2.28 on 2026-05-11 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nitrates", "0007_alter_decisiontreerevision_action_branchevalidation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchevalidation",
            name="commentaire",
        ),
        migrations.RemoveField(
            model_name="branchevalidation",
            name="valide_at",
        ),
        migrations.RemoveField(
            model_name="branchevalidation",
            name="valide_par",
        ),
        migrations.AlterField(
            model_name="branchevalidation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("non_valide", "Non validé"),
                    ("valide", "Validé"),
                    ("a_corriger", "À corriger"),
                ],
                default="non_valide",
                help_text="Statut courant : derniere action enregistree",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BrancheValidationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_valide", "Non validé"),
                            ("valide", "Validé"),
                            ("a_corriger", "À corriger"),
                        ],
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="nitrates.branchevalidation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branches_validation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Action de validation",
                "verbose_name_plural": "Actions de validation",
                "ordering": ["-created_at"],
            },
        ),
    ]
