# Generated by Django 4.2.28 on 2026-05-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0008_remove_branchevalidation_commentaire_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branchevalidation",
            options={
                "ordering": ["ordre", "chemin_yaml"],
                "verbose_name": "Validation de branche",
                "verbose_name_plural": "Validations de branches",
            },
        ),
        migrations.AddField(
            model_name="branchevalidation",
            name="ordre",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
