# Generated by Django 4.2.28 on 2026-05-22 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0010_external_observator_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrancheCulturale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.SlugField(max_length=64, unique=True)),
                (
                    "libelle_court",
                    models.CharField(
                        help_text="Libellé interne pour les juristes (non affiché user).",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ordre_affichage", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Branche culturale (arbre)",
                "verbose_name_plural": "Branches culturales (arbre)",
                "ordering": ("ordre_affichage", "identifiant"),
            },
        ),
        migrations.CreateModel(
            name="CategorieCulture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.SlugField(max_length=64, unique=True)),
                ("libelle_public", models.CharField(max_length=255)),
                (
                    "champs_prefill",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Champs à injecter dans le contexte quand cette catégorie est choisie SANS sous-culture (cas 'Sol non cultivé').",
                    ),
                ),
                ("ordre_affichage", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Catégorie de culture",
                "verbose_name_plural": "Catégories de culture",
                "ordering": ("ordre_affichage", "libelle_public"),
            },
        ),
        migrations.CreateModel(
            name="CodePrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.SlugField(max_length=16, unique=True)),
                ("mots_cles", models.CharField(blank=True, max_length=255)),
                (
                    "texte_court",
                    models.TextField(
                        help_text="Rédaction simplifiée pour affichage utilisateur."
                    ),
                ),
                (
                    "texte_redaction_initiale",
                    models.TextField(
                        blank=True, help_text="Rédaction juridique brute de l'arrêté."
                    ),
                ),
                (
                    "toujours_affiche",
                    models.BooleanField(
                        default=False,
                        help_text="Si True, ce code est affiché sur toutes les règles (prescriptions générales d'interdiction permanente).",
                    ),
                ),
                ("ordre_affichage", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Code de prescription",
                "verbose_name_plural": "Codes de prescription",
                "ordering": ("ordre_affichage", "identifiant"),
            },
        ),
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.SlugField(max_length=64, unique=True)),
                ("libelle_public", models.CharField(max_length=255)),
                (
                    "occupation_sol",
                    models.CharField(
                        choices=[
                            ("culture_principale", "Culture principale"),
                            ("couvert_intercultures", "Couvert végétal d'interculture"),
                            ("prairie", "Prairie"),
                            ("sol_non_cultive", "Sol non cultivé"),
                        ],
                        help_text="Branche niveau 1 de l'arbre YAML.",
                        max_length=32,
                    ),
                ),
                (
                    "champs_prefill",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Champs à injecter dans le contexte quand cette culture est choisie. Ex pour Maïs : {"culture_irriguee_type": "mais"}.',
                    ),
                ),
                ("ordre_affichage", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Culture",
                "verbose_name_plural": "Cultures",
                "ordering": (
                    "categorie__ordre_affichage",
                    "ordre_affichage",
                    "libelle_public",
                ),
            },
        ),
        migrations.CreateModel(
            name="EvenementPhenologique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.SlugField(max_length=64, unique=True)),
                ("libelle_public", models.CharField(max_length=255)),
                (
                    "date_calendrier",
                    models.CharField(
                        help_text="Date conventionnelle d'affichage au format JJ/MM (ex 15/08). Pas une date métier.",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format attendu : JJ/MM (ex 15/08).",
                                regex="^\\d{2}/\\d{2}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement phénologique",
                "verbose_name_plural": "Événements phénologiques",
                "ordering": ("identifiant",),
            },
        ),
        migrations.CreateModel(
            name="Fertilisant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.SlugField(max_length=64, unique=True)),
                ("libelle_public", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Note interne (post-it Miro, contexte juriste, etc.).",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("fumiers", "Fumiers"),
                            ("lisiers", "Lisiers"),
                            ("composts", "Composts"),
                            ("digestats", "Digestats"),
                            ("engrais_mineral", "Engrais minéral"),
                            ("boues", "Boues"),
                            ("autre", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "type_reglementaire",
                    models.CharField(
                        choices=[
                            ("type_0", "Type 0"),
                            ("type_Ia", "Type Ia"),
                            ("type_Ib", "Type Ib"),
                            (
                                "type_I",
                                "Type I (Ia ou Ib non distingué — usage arbre uniquement)",
                            ),
                            ("type_II", "Type II"),
                            ("type_III", "Type III"),
                        ],
                        help_text="Type PAN figé par l'arrêté. Détermine la branche type_fertilisant suivie dans l'arbre de décision. type_I interdit (réservé routage arbre).",
                        max_length=16,
                    ),
                ),
                ("ordre_affichage", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Fertilisant",
                "verbose_name_plural": "Fertilisants",
                "ordering": ("categorie", "ordre_affichage", "libelle_public"),
            },
        ),
        migrations.CreateModel(
            name="NoteReglementaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.SlugField(max_length=16, unique=True)),
                ("libelle_court", models.CharField(max_length=255)),
                ("condition_declenchement", models.TextField()),
                (
                    "regions_concernees",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Codes région INSEE (ex ['R93', 'R76']).",
                    ),
                ),
                (
                    "departements_concernes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Codes département (ex ['24', '33', '40']).",
                    ),
                ),
                ("ordre_affichage", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Note réglementaire",
                "verbose_name_plural": "Notes réglementaires",
                "ordering": ("ordre_affichage", "identifiant"),
            },
        ),
        migrations.AddConstraint(
            model_name="fertilisant",
            constraint=models.CheckConstraint(
                check=models.Q(("type_reglementaire", "type_I"), _negated=True),
                name="fertilisant_type_I_interdit",
                violation_error_message="Le type 'type_I' est réservé aux branches d'arbre regroupées (Ia ∪ Ib). Choisissez type_Ia ou type_Ib.",
            ),
        ),
        migrations.AddField(
            model_name="culture",
            name="branche_culturale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cultures",
                to="nitrates.brancheculturale",
            ),
        ),
        migrations.AddField(
            model_name="culture",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cultures",
                to="nitrates.categorieculture",
            ),
        ),
        migrations.AddField(
            model_name="codeprescription",
            name="note_reglementaire",
            field=models.ForeignKey(
                blank=True,
                help_text="Note de bas de page associée. Optionnel : à durcir en non-nullable si les juristes confirment qu'une PC a toujours une note attachée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="codes_prescription",
                to="nitrates.notereglementaire",
            ),
        ),
    ]
