# Generated by Django 4.2.28 on 2026-05-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0013_rename_categorieculture_groupecultureui"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decisiontree",
            options={
                "ordering": ["-activated_at", "-created_at"],
                "verbose_name": "Arbre de décision",
                "verbose_name_plural": "Arbres de décision",
            },
        ),
    ]
