# Generated by Django 4.2.28 on 2026-06-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0015_flatten_couverts"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchevalidation",
            name="flag_verif",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Cas special signale au seed, a verifier manuellement",
            ),
        ),
        migrations.AddField(
            model_name="branchevalidation",
            name="note_verif",
            field=models.TextField(
                blank=True,
                help_text="Detail du cas a verifier (pose par le seed, pas une action user)",
            ),
        ),
    ]
