# Generated by Django 4.2.28 on 2026-06-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0016_branchevalidation_flag_verif"),
    ]

    operations = [
        migrations.AddField(
            model_name="fertilisant",
            name="champs_prefill",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Champs à injecter dans le contexte de parcours quand ce fertilisant est choisi, pour auto-résoudre des questions complémentaires de l'arbre (ex effluent_peu_charge / effluent_peu_charge_elevage). Mêmes clés que les `champ` des nœuds `complement`. La question n'est alors pas posée mais inférée. Vide = aucune inférence.",
            ),
        ),
    ]
