# Generated by Django 4.2.28 on 2026-06-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0017_fertilisant_champs_prefill"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartementOuverture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code département INSEE (ex: '57', '2A', '971').",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100)),
                ("region_code", models.CharField(blank=True, max_length=2)),
                ("region_label", models.CharField(blank=True, max_length=100)),
                (
                    "est_ouvert",
                    models.BooleanField(
                        default=False,
                        help_text="Si vrai, le simulateur affiche le formulaire pour une parcelle de ce département. Sinon, message « pas encore ouvert ». Fermé par défaut (allowlist).",
                    ),
                ),
                ("ordre_affichage", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Ouverture département",
                "verbose_name_plural": "Ouverture départements",
                "ordering": ("region_label", "code"),
            },
        ),
    ]
