# Generated by Django 4.2.28 on 2026-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0018_branchevalidation_miro_widget_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchevalidation",
            name="scope",
            field=models.CharField(
                choices=[
                    ("national", "PAN (national)"),
                    ("par_grand_est", "PAR Grand Est"),
                    ("zar_grand_est", "ZAR Grand Est"),
                ],
                db_index=True,
                default="national",
                max_length=20,
            ),
        ),
    ]
