# Generated by Django 4.2.28 on 2026-06-15 09:04

from django.db import migrations, models
import django.db.models.deletion


def backfill_scope_national(apps, schema_editor):
    """Tous les arbres existants (PAN + son historique) deviennent national.

    Redondant avec le default des AddField, mais explicite : on garantit
    qu'aucune ligne pre-existante ne se retrouve avec un scope incoherent
    avant l'ajout des contraintes d'unicite.
    """
    DecisionTree = apps.get_model("nitrates", "DecisionTree")
    DecisionTree.objects.update(
        scope="national", region_code="", activation_map=None, weight=1
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0031_alter_map_map_type"),
        ("nitrates", "0019_seed_ouverture_grand_est"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="decisiontree",
            name="nitrates_decisiontree_unique_active",
        ),
        migrations.AddField(
            model_name="decisiontree",
            name="activation_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="geodata.map",
                verbose_name="Couche d'activation",
            ),
        ),
        migrations.AddField(
            model_name="decisiontree",
            name="region_code",
            field=models.CharField(
                blank=True, default="", max_length=3, verbose_name="Code région"
            ),
        ),
        migrations.AddField(
            model_name="decisiontree",
            name="scope",
            field=models.CharField(
                choices=[
                    ("national", "National (PAN)"),
                    ("region", "Régional (PAR)"),
                    ("zar", "Zone d'action renforcée (ZAR)"),
                ],
                default="national",
                max_length=16,
                verbose_name="Périmètre",
            ),
        ),
        migrations.AddField(
            model_name="decisiontree",
            name="weight",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Poids de résolution"
            ),
        ),
        migrations.RunPython(backfill_scope_national, noop),
        migrations.AddConstraint(
            model_name="decisiontree",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("activation_map__isnull", False), ("status", "active")
                ),
                fields=("scope", "region_code", "activation_map"),
                name="nitrates_decisiontree_unique_active_map",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisiontree",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "national"), ("status", "active")),
                fields=("scope",),
                name="nitrates_decisiontree_unique_active_national",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisiontree",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("activation_map__isnull", True),
                    ("scope", "region"),
                    ("status", "active"),
                ),
                fields=("scope", "region_code"),
                name="nitrates_decisiontree_unique_active_region_no_map",
            ),
        ),
    ]
