# Generated by Django 4.2.28 on 2026-06-18 03:59

from django.db import migrations, models


def poser_nature(apps, schema_editor):
    """Derive `nature` de l'existant : une feuille dont le chemin contient
    `q_couvert_sous_culture` est un couvert d'interculture ; le reste est de
    la culture principale. Le seed posera ensuite la valeur explicitement."""
    BrancheValidation = apps.get_model("nitrates", "BrancheValidation")
    BrancheValidation.objects.filter(
        chemin_yaml__contains="q_couvert_sous_culture"
    ).update(nature="couvert")


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0019_branchevalidation_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchevalidation",
            name="nature",
            field=models.CharField(
                choices=[
                    ("culture_principale", "Culture principale"),
                    ("couvert", "Couvert d'interculture"),
                ],
                db_index=True,
                default="culture_principale",
                max_length=20,
            ),
        ),
        migrations.RunPython(poser_nature, migrations.RunPython.noop),
    ]
