# Generated by Django 4.2.28 on 2026-06-17 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0020_decisiontree_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContenuRichDSFR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle",
                    models.CharField(
                        help_text='Identifiant stable référencé par le template (ex. "resultat.regles_permanentes"). Les points sont autorisés.',
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9]+([._-][a-z0-9]+)*$",
                                'Clé invalide : minuscules, chiffres et . _ - uniquement (ex. "resultat.regles_permanentes").',
                            )
                        ],
                    ),
                ),
                (
                    "libelle_admin",
                    models.CharField(
                        help_text="Nom lisible dans l'admin (jamais affiché côté public).",
                        max_length=255,
                    ),
                ),
                (
                    "blocs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Source unique du contenu, au format {schema, blocs:[...]}. Édité via l'éditeur WYSIWYG, jamais à la main.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contenu riche DSFR",
                "verbose_name_plural": "Contenus riches DSFR",
                "ordering": ("cle",),
            },
        ),
    ]
