# Generated by Django 4.2.28 on 2026-06-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0020_branchevalidation_nature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchevalidation",
            name="code_pc_miro",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
