# Generated by Django 4.2.28 on 2026-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0021_contenurichdsfr"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeprescription",
            name="blocs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Contenu riche (format {schema, blocs:[...]}). Édité via l'éditeur, jamais à la main. Si vide, on retombe sur texte_court.",
            ),
        ),
    ]
