# Generated by Django 4.2.28 on 2026-06-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0022_codeprescription_blocs"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchevalidation",
            name="miro_widget_id",
            field=models.CharField(
                blank=True,
                help_text="data-widget-id du board Miro (pour deeplink moveToWidget)",
                max_length=40,
            ),
        ),
    ]
