# Generated by Django 4.2.28 on 2026-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0026_code_pc_miro_max_300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchevalidation",
            name="scope",
            field=models.CharField(
                choices=[
                    ("national", "PAN (national)"),
                    ("par_grand_est", "PAR Grand Est"),
                    ("zar_grand_est", "ZAR Grand Est"),
                    ("par_hauts_de_france", "PAR Hauts-de-France"),
                ],
                db_index=True,
                default="national",
                max_length=20,
            ),
        ),
    ]
