# Generated by Django 4.2.30 on 2026-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0027_alter_branchevalidation_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeprescription",
            name="plafond",
            field=models.BooleanField(
                default=False,
                help_text="Si True, ce « code » est en réalité une RÈGLE DE PLAFOND (abus de langage : PC12 à PC16 ne sont pas de vraies prescriptions conditionnées). Conséquences d'affichage : le plafond est rendu inline sous le calendrier (pas dans le drawer des conditions) ; et si TOUTES les prescriptions d'une règle sont des plafonds, ses périodes « autorisation sous condition » sont peintes en VERT (autorisé) au lieu d'orange — le plafond s'appliquant de toute façon en période autorisée.",
            ),
        ),
    ]
