# Generated by Django 4.2.28 on 2026-08-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0028_codeprescription_plafond"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetourUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("feedback", "Feedback fin de simulation"),
                            ("interet_region", "Intérêt région non ouverte"),
                        ],
                        db_index=True,
                        help_text="Nature du retour : feedback simulation (#284) ou intérêt région (#287).",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Note d'utilité de 0 à 5 (feedback uniquement).",
                        null=True,
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire libre de l'utilisateur (feedback).",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email optionnel (alpha-testeur / alerte ouverture région). Stocké seul, jamais associé aux données de simulation.",
                        max_length=254,
                    ),
                ),
                (
                    "consentement_email",
                    models.BooleanField(
                        default=False,
                        help_text="La case de consentement RGPD a été cochée pour cet email.",
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        blank=True,
                        help_text="Code région INSEE concernée (ex : '44'). Non localisant.",
                        max_length=2,
                    ),
                ),
                (
                    "contexte",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Métadonnées anonymes (aucune donnée personnelle ni parcellaire).",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Retour utilisateur",
                "verbose_name_plural": "Retours utilisateurs",
                "ordering": ("-cree_le",),
                "indexes": [
                    models.Index(
                        fields=["type", "-cree_le"], name="nitrates_re_type_6bd7b0_idx"
                    )
                ],
            },
        ),
    ]
