# Generated by Django 4.2.30 on 2026-08-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0029_retourutilisateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeprescription",
            name="composants_fusion",
            field=models.ManyToManyField(
                blank=True,
                help_text="PC de base que cette rédaction fusionne (ex pc1_pc12 = pc1 + pc12). Quand une feuille d'arbre liste tous les composants, la fusion s'affiche à leur place. Vide pour une PC simple.",
                related_name="fusions",
                to="nitrates.codeprescription",
                verbose_name="Fusion des PC",
            ),
        ),
        migrations.AddField(
            model_name="codeprescription",
            name="region_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Guadeloupe (01)"),
                    ("02", "Martinique (02)"),
                    ("03", "Guyane (03)"),
                    ("04", "La Réunion (04)"),
                    ("06", "Mayotte (06)"),
                    ("11", "Île-de-France (11)"),
                    ("24", "Centre-Val de Loire (24)"),
                    ("27", "Bourgogne-Franche-Comté (27)"),
                    ("28", "Normandie (28)"),
                    ("32", "Hauts-de-France (32)"),
                    ("44", "Grand Est (44)"),
                    ("52", "Pays de la Loire (52)"),
                    ("53", "Bretagne (53)"),
                    ("75", "Nouvelle-Aquitaine (75)"),
                    ("76", "Occitanie (76)"),
                    ("84", "Auvergne-Rhône-Alpes (84)"),
                    ("93", "Provence-Alpes-Côte d'Azur (93)"),
                    ("94", "Corse (94)"),
                ],
                default="",
                help_text="Requis pour un périmètre régional (PAR) ou ZAR.",
                max_length=3,
                verbose_name="Région",
            ),
        ),
        migrations.AddField(
            model_name="codeprescription",
            name="scope",
            field=models.CharField(
                choices=[
                    ("national", "National (PAN)"),
                    ("region", "Régional (PAR)"),
                    ("zar", "Zone d'action renforcée (ZAR)"),
                ],
                default="national",
                help_text="Territoire où cette rédaction s'applique. Le moteur choisit, parmi une PC de base et ses déclinaisons, celle du périmètre le plus spécifique activé pour la parcelle (ZAR > PAR > PAN).",
                max_length=16,
                verbose_name="Périmètre",
            ),
        ),
        migrations.AddField(
            model_name="codeprescription",
            name="variante_de",
            field=models.ForeignKey(
                blank=True,
                help_text="PC de base dont cette ligne est la déclinaison géographique (ex pc12_zar_ge → pc12). Vide pour une PC de base.",
                limit_choices_to={"variante_de__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variantes",
                to="nitrates.codeprescription",
                verbose_name="Déclinaison de",
            ),
        ),
        migrations.AlterField(
            model_name="codeprescription",
            name="identifiant",
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AddConstraint(
            model_name="codeprescription",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("region_code", ""), ("scope", "national")),
                    models.Q(
                        models.Q(("scope", "national"), _negated=True),
                        models.Q(("region_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="codeprescription_scope_region_coherents",
                violation_error_message="Une PC nationale ne porte pas de région ; une PC régionale ou ZAR doit en porter une.",
            ),
        ),
        migrations.AddConstraint(
            model_name="codeprescription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variante_de__isnull", False)),
                fields=("variante_de", "scope", "region_code"),
                name="codeprescription_unique_variante_par_zone",
                violation_error_message="Cette PC de base a déjà une déclinaison pour cette zone d'application.",
            ),
        ),
    ]
