# Generated by Django 4.2.30 on 2026-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0031_codeprescription_remplir_zone_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenurichdsfr",
            name="categorie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fertilisants-effluents", "Fertilisants et effluents"),
                    ("azote-bilans", "Azote et bilans"),
                    ("pratique-documents", "Pratique et documents"),
                    ("reglementation-zonage", "Réglementation et zonage"),
                ],
                help_text="Section de la page Aide & définitions où ranger la définition.",
                max_length=32,
                verbose_name="catégorie",
            ),
        ),
        migrations.AddField(
            model_name="contenurichdsfr",
            name="termes_declencheurs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Variantes textuelles qui rendent le terme cliquable dans le simulateur (ex. « C/N », « rapport C/N »). Une liste de chaînes ; éditée dans l'admin en « une variante par ligne ».",
                verbose_name="termes déclencheurs",
            ),
        ),
        migrations.AddField(
            model_name="contenurichdsfr",
            name="titre_public",
            field=models.CharField(
                blank=True,
                help_text="Le terme tel qu'affiché aux usagers (ex. « Azote efficace »). Obligatoire pour une définition.",
                max_length=255,
                verbose_name="titre public",
            ),
        ),
        migrations.AddField(
            model_name="contenurichdsfr",
            name="type_contenu",
            field=models.CharField(
                choices=[("general", "Général"), ("definition", "Définition")],
                db_index=True,
                default="general",
                help_text="« Définition » = terme du glossaire, affiché sur la page Aide & définitions et cliquable dans le simulateur.",
                max_length=16,
                verbose_name="type de contenu",
            ),
        ),
    ]
