# Generated by Django 4.2.30 on 2026-09-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0033_retour_type_bug"),
    ]

    operations = [
        migrations.CreateModel(
            name="LienReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.SlugField(max_length=64, unique=True)),
                (
                    "url",
                    models.CharField(
                        help_text="URL http(s) ou chemin relatif au site (ex /static/nitrates/documents/annexe2.pdf).",
                        max_length=500,
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True,
                        help_text="Libellé par défaut du lien (informatif).",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Note de maintenance : ce que pointe ce lien, pourquoi.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien de référence",
                "verbose_name_plural": "Liens de référence",
                "ordering": ("identifiant",),
            },
        ),
    ]
