# Generated by Django 4.2.30 on 2026-10-01 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nitrates", "0036_seed_page_donnees_personnelles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouleurZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map_type",
                    models.CharField(
                        choices=[
                            ("zv_nitrates", "Zones vulnérables nitrates"),
                            ("zone_action_renforcee", "Zones d'action renforcée"),
                        ],
                        default="zv_nitrates",
                        max_length=50,
                        verbose_name="Type de carte",
                    ),
                ),
                (
                    "cle",
                    models.CharField(
                        help_text="Code bassin DCE de la zone (ex. FRA, FRB1-FRC). « * » = couleur par défaut de ce type de carte.",
                        max_length=20,
                        verbose_name="Clé de zone",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True,
                        help_text="Pour l'admin uniquement : le nom affiché vient de la zone.",
                        max_length=100,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        help_text="#rrggbb",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Couleur hexadécimale attendue, ex. #00b0ff.",
                            )
                        ],
                        verbose_name="Couleur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Couleur de zone (carte)",
                "verbose_name_plural": "Couleurs de zones (carte)",
                "ordering": ("map_type", "cle"),
            },
        ),
        migrations.AddConstraint(
            model_name="couleurzone",
            constraint=models.UniqueConstraint(
                fields=("map_type", "cle"), name="couleur_zone_unique_par_cle"
            ),
        ),
    ]
