from django.urls import path
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from envergo.nitrates.views import (
    DebugView,
    DecisionTreeView,
    HomeView,
    MoulinetteView,
    ReferentielsView,
    ZoneVulnerableGeoJSONView,
)
from envergo.nitrates.views_admin_yaml import (
    CancelEditView,
    CloneConfirmView,
    CreateDraftView,
    EditActiveView,
    RenameTreeView,
    YamlTreeView,
)
from envergo.nitrates.views_admin_yaml_edit import (
    AddChildView,
    CancelAddChildView,
    CancelEditBrancheView,
    CancelEditNodeView,
    CancelEditRegleView,
    EditBrancheView,
    EditNodeView,
    EditRegleView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path(
        _("simulateur/"),
        MoulinetteView.as_view(),
        name="nitrates_simulateur",
    ),
    path(
        _("simulateur/debug/"),
        DebugView.as_view(),
        name="nitrates_debug",
    ),
    path(
        "geojson/zv/",
        ZoneVulnerableGeoJSONView.as_view(),
        name="nitrates_zv_geojson",
    ),
    path(
        "api/referentiels/",
        ReferentielsView.as_view(),
        name="nitrates_referentiels",
    ),
    path(
        "api/arbre/",
        DecisionTreeView.as_view(),
        name="nitrates_arbre",
    ),
    path(
        "admin/nitrates/arbre-decision/",
        YamlTreeView.as_view(),
        name="nitrates_admin_yaml_tree",
    ),
    path(
        "admin/nitrates/arbre-decision/draft/nouveau/",
        CreateDraftView.as_view(),
        name="nitrates_admin_yaml_create_draft",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:pk>/renommer/",
        RenameTreeView.as_view(),
        name="nitrates_admin_yaml_rename_tree",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:pk>/cloner/",
        CloneConfirmView.as_view(),
        name="nitrates_admin_yaml_clone_confirm",
    ),
    path(
        "admin/nitrates/arbre-decision/editer-actif/",
        EditActiveView.as_view(),
        name="nitrates_admin_yaml_edit_active",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:pk>/sortir-edition/",
        CancelEditView.as_view(),
        name="nitrates_admin_yaml_cancel_edit",
    ),
    # Endpoints htmx d'edition inline (etape 5c).
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/noeud/",
        EditNodeView.as_view(),
        name="nitrates_admin_yaml_edit_node",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/noeud/cancel/",
        CancelEditNodeView.as_view(),
        name="nitrates_admin_yaml_edit_node_cancel",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/regle/",
        EditRegleView.as_view(),
        name="nitrates_admin_yaml_edit_regle",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/regle/cancel/",
        CancelEditRegleView.as_view(),
        name="nitrates_admin_yaml_edit_regle_cancel",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/branche/",
        EditBrancheView.as_view(),
        name="nitrates_admin_yaml_edit_branche",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/branche/cancel/",
        CancelEditBrancheView.as_view(),
        name="nitrates_admin_yaml_edit_branche_cancel",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/add-child/",
        AddChildView.as_view(),
        name="nitrates_admin_yaml_add_child",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/add-child/cancel/",
        CancelAddChildView.as_view(),
        name="nitrates_admin_yaml_add_child_cancel",
    ),
    path(
        _("contact-us/"),
        TemplateView.as_view(template_name="nitrates/contact_us.html"),
        name="contact_us",
    ),
]
