from django.urls import path
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from envergo.nitrates.views import (
    DebugView,
    DecisionTreeView,
    HomeView,
    MoulinetteView,
    ReferentielsView,
    ZoneActionRenforceeGeoJSONView,
    ZoneVulnerableGeoJSONView,
)
from envergo.nitrates.views_admin_ouverture import (
    ouverture_index,
    ouverture_toggle,
    ouverture_toggle_region,
)
from envergo.nitrates.views_admin_validation import (
    validation_create,
    validation_delete,
    validation_detail,
    validation_edit_meta,
    validation_index,
    validation_set_statut,
    validation_upload_miro,
    validation_upload_playwright,
    validation_upload_yaml_form,
    validation_upload_yaml_viewer,
)
from envergo.nitrates.views_admin_yaml import (
    CancelEditView,
    CloneConfirmView,
    CreateDraftView,
    EditActiveView,
    RenameTreeView,
    YamlTreeView,
)
from envergo.nitrates.views_admin_yaml_edit import (
    ActivateTreeView,
    AddChildView,
    CancelAddChildView,
    CancelChangeBranchContentView,
    CancelEditBrancheView,
    CancelEditNodeView,
    CancelEditRegleView,
    CancelInsertParentView,
    ChangeBranchContentView,
    ConvertNodeView,
    DeleteBrancheView,
    DeleteNodeView,
    EditBrancheView,
    EditNodeView,
    EditRawYamlView,
    EditRegleView,
    InsertParentView,
    ReorderBranchesView,
    RestoreRevisionView,
    UndoLastView,
    ValidateTreeView,
)
from envergo.nitrates.views_contenu_rich_preview import ContenuRichPreviewView
from envergo.nitrates.views_yaml_browser import (
    YamlBrowserDetailView,
    YamlBrowserListView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path(
        _("simulateur/"),
        MoulinetteView.as_view(),
        name="nitrates_simulateur",
    ),
    path(
        _("simulateur/debug/"),
        DebugView.as_view(),
        name="nitrates_debug",
    ),
    path(
        "geojson/zv/",
        ZoneVulnerableGeoJSONView.as_view(),
        name="nitrates_zv_geojson",
    ),
    path(
        "geojson/zar/",
        ZoneActionRenforceeGeoJSONView.as_view(),
        name="nitrates_zar_geojson",
    ),
    path(
        "api/referentiels/",
        ReferentielsView.as_view(),
        name="nitrates_referentiels",
    ),
    path(
        "api/arbre/",
        DecisionTreeView.as_view(),
        name="nitrates_arbre",
    ),
    path(
        "admin/nitrates/contenu-rich/preview/",
        ContenuRichPreviewView.as_view(),
        name="nitrates_admin_contenu_rich_preview",
    ),
    path(
        "admin/nitrates/arbre-decision/",
        YamlTreeView.as_view(),
        name="nitrates_admin_yaml_tree",
    ),
    path(
        "admin/nitrates/arbre-decision/draft/nouveau/",
        CreateDraftView.as_view(),
        name="nitrates_admin_yaml_create_draft",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:pk>/renommer/",
        RenameTreeView.as_view(),
        name="nitrates_admin_yaml_rename_tree",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:pk>/cloner/",
        CloneConfirmView.as_view(),
        name="nitrates_admin_yaml_clone_confirm",
    ),
    path(
        "admin/nitrates/arbre-decision/editer-actif/",
        EditActiveView.as_view(),
        name="nitrates_admin_yaml_edit_active",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:pk>/sortir-edition/",
        CancelEditView.as_view(),
        name="nitrates_admin_yaml_cancel_edit",
    ),
    # Endpoints htmx d'edition inline (etape 5c).
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/noeud/",
        EditNodeView.as_view(),
        name="nitrates_admin_yaml_edit_node",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/noeud/cancel/",
        CancelEditNodeView.as_view(),
        name="nitrates_admin_yaml_edit_node_cancel",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/regle/",
        EditRegleView.as_view(),
        name="nitrates_admin_yaml_edit_regle",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/regle/cancel/",
        CancelEditRegleView.as_view(),
        name="nitrates_admin_yaml_edit_regle_cancel",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/branche/",
        EditBrancheView.as_view(),
        name="nitrates_admin_yaml_edit_branche",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/branche/cancel/",
        CancelEditBrancheView.as_view(),
        name="nitrates_admin_yaml_edit_branche_cancel",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/add-child/",
        AddChildView.as_view(),
        name="nitrates_admin_yaml_add_child",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/add-child/cancel/",
        CancelAddChildView.as_view(),
        name="nitrates_admin_yaml_add_child_cancel",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/delete-branche/",
        DeleteBrancheView.as_view(),
        name="nitrates_admin_yaml_delete_branche",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/insert-parent/",
        InsertParentView.as_view(),
        name="nitrates_admin_yaml_insert_parent",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/insert-parent/cancel/",
        CancelInsertParentView.as_view(),
        name="nitrates_admin_yaml_insert_parent_cancel",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/change-content/",
        ChangeBranchContentView.as_view(),
        name="nitrates_admin_yaml_change_content",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/change-content/cancel/",
        CancelChangeBranchContentView.as_view(),
        name="nitrates_admin_yaml_change_content_cancel",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/delete-noeud/",
        DeleteNodeView.as_view(),
        name="nitrates_admin_yaml_delete_node",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/convert-catalogue-parametre/",
        ConvertNodeView.as_view(),
        name="nitrates_admin_yaml_convert_catalogue_parametre",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/reorder-branches/",
        ReorderBranchesView.as_view(),
        name="nitrates_admin_yaml_reorder_branches",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/undo/",
        UndoLastView.as_view(),
        name="nitrates_admin_yaml_undo",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/restore/",
        RestoreRevisionView.as_view(),
        name="nitrates_admin_yaml_restore_revision",
    ),
    # Mini browser YAML pleine page (dev) : liste -> detail avec
    # CodeMirror + theme Darcula. Endpoint temporaire.
    path(
        "yaml-browser/",
        YamlBrowserListView.as_view(),
        name="nitrates_yaml_browser_list",
    ),
    path(
        "yaml-browser/<int:pk>/",
        YamlBrowserDetailView.as_view(),
        name="nitrates_yaml_browser_detail",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/validate/",
        ValidateTreeView.as_view(),
        name="nitrates_admin_yaml_validate_tree",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/activate/",
        ActivateTreeView.as_view(),
        name="nitrates_admin_yaml_activate_tree",
    ),
    path(
        "admin/nitrates/arbre-decision/<int:tree_pk>/edit/raw-yaml/",
        EditRawYamlView.as_view(),
        name="nitrates_admin_yaml_edit_raw",
    ),
    path(
        _("contact-us/"),
        TemplateView.as_view(template_name="nitrates/contact_us.html"),
        name="contact_us",
    ),
    # Validation manuelle des feuilles (issue #28 / sprint MVP-1 fin)
    path(
        "admin/nitrates/validation/",
        validation_index,
        name="nitrates_admin_validation_index",
    ),
    path(
        "admin/nitrates/validation/ajouter/",
        validation_create,
        name="nitrates_admin_validation_create",
    ),
    path(
        "admin/nitrates/validation/<int:pk>/",
        validation_detail,
        name="nitrates_admin_validation_detail",
    ),
    path(
        "admin/nitrates/validation/<int:pk>/supprimer/",
        validation_delete,
        name="nitrates_admin_validation_delete",
    ),
    path(
        "admin/nitrates/validation/<int:pk>/statut/",
        validation_set_statut,
        name="nitrates_admin_validation_set_statut",
    ),
    path(
        "admin/nitrates/validation/<int:pk>/upload-miro/",
        validation_upload_miro,
        name="nitrates_admin_validation_upload_miro",
    ),
    path(
        "admin/nitrates/validation/<int:pk>/upload-yaml-viewer/",
        validation_upload_yaml_viewer,
        name="nitrates_admin_validation_upload_yaml_viewer",
    ),
    path(
        "admin/nitrates/validation/<int:pk>/upload-yaml-form/",
        validation_upload_yaml_form,
        name="nitrates_admin_validation_upload_yaml_form",
    ),
    path(
        "admin/nitrates/validation/<int:pk>/upload-playwright/",
        validation_upload_playwright,
        name="nitrates_admin_validation_upload_playwright",
    ),
    path(
        "admin/nitrates/validation/<int:pk>/edit-meta/",
        validation_edit_meta,
        name="nitrates_admin_validation_edit_meta",
    ),
    # Bornage géographique du simulateur (carte #57).
    path(
        "admin/nitrates/ouverture-geographique/",
        ouverture_index,
        name="nitrates_admin_ouverture_index",
    ),
    path(
        "admin/nitrates/ouverture-geographique/toggle/",
        ouverture_toggle,
        name="nitrates_admin_ouverture_toggle",
    ),
    path(
        "admin/nitrates/ouverture-geographique/toggle-region/",
        ouverture_toggle_region,
        name="nitrates_admin_ouverture_toggle_region",
    ),
]
